[package]
name = "vinput-asr"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []
sherpa-onnx-backend = ["dep:sherpa-onnx"]

[dependencies]
reqwest.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
sherpa-onnx = { workspace = true, optional = true }
thiserror.workspace = true
vinput-audio = { path = "../vinput-audio" }
vinput-protocol = { path = "../vinput-protocol" }
vinput-config = { path = "../vinput-config" }
vinput-http = { path = "../vinput-http" }


[dev-dependencies]
tempfile.workspace = true
